version: "3.9"

services:
  app:
    container_name: sistema-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: ["npm", "start"]

  db:
    image: mysql:8.0
    container_name: sistema-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./identificacao_estudantes:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${DB_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sistema-phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    restart: always

  noip:
    image: ghcr.io/noipcom/noip-duc:3.3.0
    container_name: noip-duc
    restart: always
    environment:
      NOIP_USERNAME: "${NOIP_USERNAME}"
      NOIP_PASSWORD: "${NOIP_PASSWORD}"
      NOIP_HOSTNAMES: "${NOIP_HOSTNAMES}"
      NOIP_INTERVAL: "300"

volumes:
  mysql_data:
